{{ $deployment := .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment.name }}
  namespace: {{ $deployment.namespace }}
  labels:
  {{ toYaml $deployment.labels | nindent 4 }}    
spec:
  selector:
    matchLabels:
    {{ toYaml $deployment.selectorLabels | nindent 6 }}
  replicas: {{ $deployment.replicas }}
  strategy:
    type: {{ $deployment.strategyType }}
    rollingUpdate:
      maxSurge: {{ $deployment.maxSurge }}
      maxUnavailable: {{ $deployment.maxUnavailable }}
  template:
    metadata:
      labels:
      {{ toYaml $deployment.selectorLabels | nindent 8 }}
      annotations:
      {{ toYaml $deployment.annotations | nindent 8 }}
    spec:
      {{ if $deployment.serviceAccount }}
      serviceAccountName: {{ $deployment.serviceAccount }}
      {{ end }}
      {{ if $deployment.nodeSelector }}
      nodeSelector:
      {{ toYaml $deployment.nodeSelector | nindent 8 }}
      {{ end }}
      containers:
      {{ range $container := $deployment.containers }}
      - name: {{ $container.name }}
        image: {{ $container.image }}
        imagePullPolicy: {{ $container.imagePullPolicy }}
        resources:
          requests:
            memory: {{ $container.memoryRequest }}
            cpu: {{ $container.cpuRequest }}
          limits:
            memory: {{ $container.memoryLimit }}
            cpu: {{ $container.cpuLimit }}
        {{ if $container.readinessProbe }}
        readinessProbe:
          {{ if $container.readinessProbe.commands }}
          exec:
            command:
            {{ toYaml $container.readinessProbe.commands | nindent 12 }}
        {{ end }}
        {{ if $container.readinessProbe.httpGet }}
          httpGet:
            port: {{ $container.readinessProbe.httpGet.port }}
            path: {{ $container.readinessProbe.httpGet.path }}
        {{ end }}
        {{ end }}
        {{ if $container.livenessProbe }}
        livenessProbe:
        {{ if $container.livenessProbe.commands }}
          exec:
            command:
            {{ toYaml $container.livenessProbe.commands | nindent 12 }}
        {{ end }}
        {{ if $container.livenessProbe.httpGet }}
          httpGet:
            port: {{ $container.livenessProbe.httpGet.port }}
            path: {{ $container.livenessProbe.httpGet.path }}
        {{ end }}
        {{ end }}
        ports:
        {{ range $containerPort := $container.containerPorts }}
        - containerPort: {{ $containerPort }}
        {{ end }}
        {{ if $container.envVarsFrom }}
        envFrom:        
        {{ toYaml $container.envVarsFrom | nindent 8 }}
        {{ end }}
        {{ if $container.envVars }}
        env:
        {{ range $env := $container.envVars }}
        - name: {{ $env.name }}
          value: {{ quote $env.value }}
        {{ end }}
        {{ end }}
        {{ if $container.volumeMounts }}
        volumeMounts:
        {{ toYaml $container.volumeMounts | nindent 8 }}
        {{ end }}
      {{ if $deployment.volumes }}
      volumes:
      {{ toYaml $deployment.volumes | nindent 6 }}
      {{ end }}
      {{ end }}    
