{{ if .Values.ingress }}
{{ $ingress := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingress.name }}
  annotations:
  {{ toYaml $ingress.annotations | nindent 4 }}    
spec:
  ingressClassName: {{ $ingress.ingressClassName}}
  rules:
  {{ range $rule := $ingress.rules }}
  - host: {{ $rule.host }}
    http:
      paths:
      {{ range $path := $rule.paths }}
      - pathType: {{ $path.pathType }}
        path: {{ $path.path }}
        backend:
          service:
            name: {{ $path.serviceName }}
            port:
              number: {{ $path.servicePort }}
      {{ end }}
  {{ end }}
  {{ end }}
    
    
