deployment:
  name: nginxapp-deploy
  serviceAccount: smoke-sa
  labels:
    app: nginxapp-deploy
    version: v1
  selectorLabels:
    app: nginxapp-pod
    version: v1
  replicas: 1
  strategyType: RollingUpdate
  maxSurge: 1
  maxUnavailable: 0
  nodeSelector:
    cloud.google.com/gke-nodepool: worker-pool
  containers:
  - name: nginx-app
    image: "nginx:latest"
    imagePullPolicy: IfNotPresent
    memoryRequest: "250Mi"
    cpuRequest: "100m"
    memoryLimit: "500Mi"
    cpuLimit: "200m"
    containerPorts: [80]
    readinessProbe:
      commands:
      - curl
      - -f
      - localhost:80
    livenessProbe:
      commands:
      - curl
      - -f
      - localhost:80    
service:
  name: nginxapp-svc
  selector:
    app: nginxapp-pod
  type: ClusterIP  
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
    