steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Authorize Cloud Build'
    entrypoint: 'bash'
    args:
      - -c
      - |
        apt-get install dnsutils jq -y &&
        cloudbuild_external_ip=$(dig @resolver4.opendns.com myip.opendns.com +short) &&
        old_cidr=$(gcloud container clusters describe ${_CLUSTER_NAME_} --zone=${_REGION_} --format json | jq -r '.masterAuthorizedNetworksConfig.cidrBlocks[] | .cidrBlock' | tr '\n' ',') &&
        gcloud container clusters update ${_CLUSTER_NAME_} --zone=${_REGION_} --enable-master-authorized-networks --master-authorized-networks "$old_cidr$cloudbuild_external_ip/32"
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-credentials'
    args: ['container', 'clusters', 'get-credentials', '${_CLUSTER_NAME_}', '--project=${_PROJECT_ID_}', '--region=${_REGION_}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'install-ingress'
    entrypoint: 'bash'
    args:
      - -c
      - |
        bash ./deployments/scripts/destroy.sh
    waitFor:
      - 'get-credentials'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Remove worker cidr'
    entrypoint: 'bash'
    waitFor: 'install-ingress'
    args:
      - -c
      - |
        apt-get install dnsutils jq -y &&
        cloudbuild_external_ip=$(dig @resolver4.opendns.com myip.opendns.com +short) &&
        old_cidr=$(gcloud container clusters describe ${_CLUSTER_NAME_} --zone=${_REGION_} --format json | jq 'del(.masterAuthorizedNetworksConfig.cidrBlocks[] | select(.cidrBlock == "'"$cloudbuild_external_ip/32"'"))' | jq -r '.masterAuthorizedNetworksConfig.cidrBlocks[] | .cidrBlock' | tr '\n' ','  | sed 's/,$//' ) &&
        gcloud container clusters update ${_CLUSTER_NAME_} --zone=${_REGION_} --enable-master-authorized-networks --master-authorized-networks "$old_cidr"
tags: ['cloud-builders-community']
serviceAccount: "projects/${_PROJECT_ID_}/serviceAccounts/${_PROJECT_ID_}-sa@${_PROJECT_ID_}.iam.gserviceaccount.com"
logsBucket: "gs://${_LOG_BUCKET_}"
substitutions:
  _PROJECT_ID_: ''
  _REGION_: ''
  _CLUSTER_NAME_: ''  
  _HELM_CHART_NAME_: ''
  _K8S_NAMESPACE_: ''
  _LOG_BUCKET_: ''
options:
    dynamicSubstitutions: true
    # pool:
    #   name: 'projects/${_PROJECT_ID_}/locations/${_REGION_}/workerPools/${_PROJECT_ID_}-build-pool'