steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-credentials'
    args: ['container', 'clusters', 'get-credentials', '${_CLUSTER_NAME_}', '--project=${_PROJECT_ID_}', '--region=${_REGION_}', '--internal-ip']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'keycloak-setup'
    entrypoint: 'bash'
    waitFor: 'get-credentials'
    args:
      - -c
      - bash deployments/scripts/keycloak-init.sh ${_DOMAIN_}
tags: ['cloud-builders-community']
serviceAccount: "projects/${_PROJECT_ID_}/serviceAccounts/${_SERVICE_ACCOUNT_}"
logsBucket: "gs://${_LOG_BUCKET_}"
substitutions:
  _PROJECT_ID_: ''
  _REGION_: ''
  _CLUSTER_NAME_: 'functional-registry-cluster'
  _DOMAIN_: ''
  _LOG_BUCKET_: ''
  _SERVICE_ACCOUNT_: ''
  _NAME_: 'functional-registry'
options:
    dynamicSubstitutions: true
    pool:
      name: 'projects/${_PROJECT_ID_}/locations/${_REGION_}/workerPools/${_NAME_}-cloudbuild-private-worker-pool'
